server:
  port: 8080

app:
  api-prefix: /api/v1
  web-client-url: lb://auth-service
  cors:
    allowed-origins: http://localhost:3000
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Gateway, API-Gateway

        # USER-SERVICE
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Gateway, API-Gateway

        # PRODUCT-SERVICE
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
          filters:
            - RewritePath=/api/v1/products/(?<segment>.*), /${segment}
            - AddRequestHeader=X-Gateway, API-Gateway
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
