server:
  port: 8081
  servlet:
    context-path: /auth
app:
  services:
    profile: ${PROFILE_SERVICE}
    file: ${FILE_SERVICE}
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  cache:
    type: redis

  data:
    mongodb:
      uri: mongodb://root:abc123%21%40%23@localhost:27017/ecommerce?authSource=admin
    redis:
      host: redis
      port: 6379
      password: myredispass
      repositories:
        enabled: false
      ssl:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: false

  application:
    name: auth-service
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 3600000     # 1 h in milliseconds
        refresh-token:
          expiration: 604800000 # 7 days in milliseconds
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8080/issuer