server:
  port: 8083


spring:
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
  cache:
    type: redis

  data:
    mongodb:
      uri: mongodb://root:abc123456@localhost:27017/file-service?authSource=admin

  minio:
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: admin@2024
    bucket-name: resources